### ISSUE TITLE
Overlays not appearing on all current recordings

### ISSUE THREAD

**Issue by denz2** [MediaBrowser/emby-theater-windows#362]
For some reason the overlays not appearing on all recordings and it looks incomplete. The overlays also includes info that is not necessary like anger management has (2014)

![capture no overlay](https://cloud.githubusercontent.com/assets/16771401/17266575/6074c438-562c-11e6-8ffb-4fef96eca4a6.PNG)

**Comment by LukePulverenti** [comment]
This has been resolved. Please let me know if you see otherwise. Thanks.
