### ISSUE TITLE
Deleting a recording from recordings screen takes you back to home screen 

### ISSUE THREAD

**Issue by denz2** [MediaBrowser/emby-theater-windows#386]
When you are in recordings screen outside live TV and you delete a show it takes you to home screen instead of going back to the  position near the show you just deleted.

**Comment by LukePulverenti** [comment]
We are working on improving automatic screen refreshing in response to various actions (e.g, delete, mark watch/favorite, add new item, etc). This will be resolved as part of this:



https://github.com/MediaBrowser/Emby/issues/3038



Thanks.
