### ISSUE TITLE
Deleting a recording from live TV screen takes you to the shows screen. 

### ISSUE THREAD

**Issue by denz2** [MediaBrowser/emby-theater-windows#387]
When you delete a recording from live TV instead of being in the same screen it takes you to the show screen

**Comment by LukePulverenti** [comment]
We are working on improving automatic screen refreshing in response to various actions (e.g, delete, mark watch/favorite, add new item, etc). This will be resolved as part of this:



https://github.com/MediaBrowser/Emby/issues/3038



Thanks.
