### ISSUE TITLE
Play next episode automatically can't be disabled

### ISSUE THREAD

**Issue by Doofussy2** [MediaBrowser/emby-theater-windows#401]
Deselecting 'Play next episode automatically' doesn't disable the feature. The next episode is always automatically played.

Theater 3.0.11

![Annotation 2020-04-03 215416](https://user-images.githubusercontent.com/15950919/78418954-c160b800-75f5-11ea-9b06-b44da96025b4.jpg)

**Comment by Doofussy2** [comment]
This is still a problem.

**Comment by LukePulverenti** [comment]
Sorry for the delay. I will get to this.

**Comment by Doofussy2** [comment]
Still broken.

**Comment by Doofussy2** [comment]
This appears to be fixed.

**Comment by Doofussy2** [comment]
Nope, still broken.

**Comment by Doofussy2** [comment]
I really want this to be fixed. It's such a pain.

**Comment by Doofussy2** [comment]
@LukePulverenti , please fix this.

**Comment by Doofussy2** [comment]
I'm really trying not to be pain, but it's been four months. Is this so difficult to fix, that it's going to be ignored?

**Comment by Doofussy2** [comment]
I give up. Closing

**Comment by LukePulverenti** [comment]
Apologies for the delay. I'll be looking at this soon.

**Comment by Doofussy2** [comment]
Another month has gone by.... :/

**Comment by Doofussy2** [comment]
@LukePulverenti please fix this this. It's a big problem :(

**Comment by Doofussy2** [comment]
Can this be fixed, please?

**Comment by Doofussy2** [comment]
For f*** sake, fix this already! It's been almost a year!

**Comment by LukePulverenti** [comment]
Apologies, I'll be reviewing this soon.
