### ISSUE TITLE
HDR rendering is interfered with

### ISSUE THREAD

**Issue by Doofussy2** [MediaBrowser/emby-theater-windows#404]
It appears that HDR metadata and/or render of the metadata is being interfered with. Note the discolored squares.

![IMG_20200509_200151](https://user-images.githubusercontent.com/15950919/82720879-829dc480-9c6c-11ea-8c52-b7462ce413fe.jpg)

![IMG_20200509_203113](https://user-images.githubusercontent.com/15950919/82720886-8d585980-9c6c-11ea-94dd-a09045f9751a.jpg)

This doesn't occur directly in mpv. I suspect that electron is the cause. I've tried more recent electron releases, but it still happens.

**Comment by LukePulverenti** [comment]
Is this with the release version or the new test build?

**Comment by Doofussy2** [comment]
With the release. HDR doesn't work in the test build.

**Comment by Doofussy2** [comment]
It would be a very good idea if you followed through on adding the HDR for external players option.

**Comment by Doofussy2** [comment]
If I see one of those squares and then bring up the OSD, the square goes away.

**Comment by LukePulverenti** [comment]
Can you try the test app again, and enable the option i mention here?
https://emby.media/community/index.php?/topic/46763-theater-mpv-test/?p=889403
Thanks.

**Comment by Doofussy2** [comment]
That brings back the use of gpu rendering and HDR works again, but doesn't fix the issue I reported.

**Comment by Doofussy2** [comment]
I'm now using mpv directly, for HDR content.

**Comment by LukePulverenti** [comment]
Is the square always in the same spot? Is it always just one square?

**Comment by Doofussy2** [comment]
No, different media, different scenes, different position. 

Oh hold up! I think I just accidentally figured this out. It appears to be the mouse cursor position. I positioned the cursor in a specific place, played the video, and the square appeared in the same position. With the square visible, when moving the cursor, the square disappears. So the square appears to be caused by the mouse cursor.

**Comment by Doofussy2** [comment]
This is the mouse that I have;

https://www.amazon.com/Logitech-M570-Wireless-Trackball-Mouse/dp/B0043T7FXE/ref=sr_1_5?crid=26G42FYBO6SLX&dchild=1&keywords=logitech+mouse+wireless&qid=1591070391&sprefix=logitech+mouse%2Caps%2C203&sr=8-5

**Comment by Doofussy2** [comment]
And this is how it's configured in Windows

![Annotation 2020-06-01 210130](https://user-images.githubusercontent.com/15950919/83478637-32ccb380-a44b-11ea-9a1a-6d294b1e208e.jpg)

**Comment by Doofussy2** [comment]
Yup! That's what it is! If you pause playback (best on a bright scene), position the cursor then let the cursor disappear, you'll see the square. 100% repeatable.

**Comment by Doofussy2** [comment]
I just discovered this is happening in VLC, too. So this maybe a Windows bug. It doesn't happen in mpv, but I think it's because the interface is entirely different, and doesn't have an overlay.

**Comment by Doofussy2** [comment]
This appears to have been resolved. For reference: I have an Nvidia RTX 2060. Windows 10 2004 now uses DirectX 12 Ultimate. Nvidia has just released a driver (451.48) that supports/utilizes DirectX 12 Ultimate, on  06/24/2020. I installed it, and now I cannot reproduce this issue. So I will tentatively say that this was an Nvidia driver issue....???

**Comment by Doofussy2** [comment]
I'm going to close this. It appears to have been a GPU drive glitch.
