### ISSUE TITLE
Audio delay doesn't work

### ISSUE THREAD

**Issue by Doofussy2** [MediaBrowser/emby-theater-windows#410]
The audio delay in the video settings doesn't work, and the option is being negated in an mpv.conf by Theater.

**Comment by LukePulverenti** [comment]
Hi, this works in our testing with 2000 and -2000 ms. Perhaps it's caused by some combination of settings in mpv.conf ?

**Comment by Doofussy2** [comment]
Are you forcing milliseconds? The docs say to use seconds, not milliseconds.

https://mpv.io/manual/master/#options-audio-delay

![Screenshot 2021-02-21 190324](https://user-images.githubusercontent.com/15950919/108651926-a8642e00-7477-11eb-9d10-b8c2bc07a3a2.jpg)

**Comment by Doofussy2** [comment]
Ah geez! Why are you ignoring the documentation? 

![Screenshot 2021-02-21 190726](https://user-images.githubusercontent.com/15950919/108652112-32ac9200-7478-11eb-86b0-d9f82cd5e11f.jpg)

**Comment by LukePulverenti** [comment]
The value you configure in our UI has nothing to do with how we communicate with mpv.

**Comment by Doofussy2** [comment]
Well that's bad!

I guess you close this...

**Comment by LukePulverenti** [comment]
We are passing in seconds to answer the previous question.

**Comment by Doofussy2** [comment]
So we put milliseconds in the app and you convert it to seconds to pass it to mpv? That doesn't make sense. Just use seconds like the docs request.

**Comment by LukePulverenti** [comment]
Nonetheless, that doesn't relate to whether the option is working or not working.

**Comment by Doofussy2** [comment]
Yeah, I said you can close it.
